### ISSUE TITLE
npm run structor error

### ISSUE THREAD

**Issue by cwtuan** [ipselon/structor#101]
After run these commands:
```
npm install
npm install structor
npm run structor
```

Got the error:

```
 npm run structor

> starter-app@0.0.1 structor /Users/tony/workspace/github/structor/structor-starter
> structor

module.js:471
    throw err;
    ^

Error: Cannot find module 'babel-register'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/tony/workspace/github/structor/structor-starter/node_modules/structor/server/controller.js:1:2639)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

**Comment by cwtuan** [comment]
node v6.10.0 @ mac
