### ISSUE TITLE
Keep getting "Loading"

### ISSUE THREAD

**Issue by kpennell** [ipselon/structor#109]
Makes it pretty hard to want to use this when I've hit this loading error 2x already, forcing me to ditch project and restart. 

![image](https://user-images.githubusercontent.com/1060385/31320790-4882f1a6-ac2f-11e7-9150-508912493d6c.png)

**Comment by sumeetakumar** [comment]
I am getting the same error/. I am on Windows 10 with nodejs v8.8.1 and just cloned this repo today. TIA

**Comment by sumeetakumar** [comment]
ok, i fixed my issue:
1) changed package.json file to "structor -v" as recommended in another issue
2) npm run structor showed error for a module not found (forgot which)
3) recloned git in a new directory, and used "npm install" instead of using "yarn install" used earlier on my own initiative. followed by "npm install structor"
4) "npm run structor" ran without any errors
5) browser page loaded fully without any issues

**Comment by medington** [comment]
Running into this as well. I "fixed" the issue once by starting over with a fresh clone / npm install but it came back. Is there some state file I can delete to get past this? I'm just trying to walk through the steps in the Readme file so nothing complicated!

Here are the 2 most interesting stack traces in dev tools (there are others too):

```
main.js:11 uncaught at i TypeError: Cannot read property 'forEach' of undefined
    at t.value (http://localhost:2222/structor/main.js:28:110345)
    at f._renderValidatedComponentWithoutOwnerOrContext (http://localhost:2222/structor/main.js:33:549456)
    at f._renderValidatedComponent (http://localhost:2222/structor/main.js:33:549583)
    at f.performInitialMount (http://localhost:2222/structor/main.js:33:545424)
    at f.mountComponent (http://localhost:2222/structor/main.js:33:544470)
    at Object.mountComponent (http://localhost:2222/structor/main.js:11:76900)
    at f.performInitialMount (http://localhost:2222/structor/main.js:33:545584)
    at f.mountComponent (http://localhost:2222/structor/main.js:33:544470)
    at Object.mountComponent (http://localhost:2222/structor/main.js:11:76900)
    at h.mountChildren (http://localhost:2222/structor/main.js:33:575226)

warning.js?9853:10 Store does not have a valid reducer. Make sure the argument passed to combineReducers is an object whose values are reducers.
warning @ warning.js?9853:10
combination @ combineReducers.js?a3f5:109
dispatch @ createStore.js?8c3f:166
createStore @ createStore.js?8c3f:240
(anonymous) @ applyMiddleware.js?701c:28
createStore @ createStore.js?8c3f:52
configureStore @ store.js?41db:30
window.__createPageDesk @ default.js?7066:23
```
