### ISSUE TITLE
ReferenceError: Promise is not defined  on Ubuntu 14.04 and node v0.10.25

### ISSUE THREAD

**Issue by allan-simon** [ipselon/structor#11]
When I try to launch structor, it opens and tell me there's a problem about current directory, and when I check the terminal, I got plenty of 
```
ReferenceError: Promise is not defined
    at e._createClass.value (/usr/local/lib/node_modules/structor/server/FileManager.js:1:4496)
    at e._createClass.value (/usr/local/lib/node_modules/structor/server/StorageManager.js:1:8458)
    at e._createClass.value (/usr/local/lib/node_modules/structor/server/api.js:1:4064)
    at /usr/local/lib/node_modules/structor/server/api.js:1:3507
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/structor/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/local/lib/node_modules/structor/node_modules/express/lib/router/route.js:131:13)
    at /usr/local/lib/node_modules/structor/node_modules/body-parser/lib/read.js:129:5
    at invokeCallback (/usr/local/lib/node_modules/structor/node_modules/body-parser/node_modules/raw-body/index.js:262:16)
    at done (/usr/local/lib/node_modules/structor/node_modules/body-parser/node_modules/raw-body/index.js:251:7)
    at IncomingMessage.onEnd (/usr/local/lib/node_modules/structor/node_modules/body-parser/node_modules/raw-body/index.js:308:7)
```

is it because my node version is too old ?

**Comment by ipselon** [comment]
Yes, definitely.

**Comment by ipselon** [comment]
@allan-simon did you resolve this issue ?

**Comment by allan-simon** [comment]
not yet, I think when I will get some times I will try to create a dockerfile, that will ease things.

**Comment by ipselon** [comment]
Do you mean that upgrading node.js to version > 12.2 didn't solve your problem ?

**Comment by allan-simon** [comment]
no it's just that I currently have other things that i need on a daily basis that works fine with my current version of node and my previous experiences upgrading node version have been chaotic (random packet which stop working) so I'm a bit reluctant to upgrade it fully, and i would prefer so to have all of that in a container so that to be sure to not have side effects :)

**Comment by ipselon** [comment]
OK. Thanks
