### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by yashwanth2804** [ipselon/structor#130]
```
 ⚠ EACCES: permission denied, mkdir '/home/hasura/Videos/UIBuilder/structor/node_modules/pngquant-bin/vendor'
  ⚠ pngquant pre-build test failed
  ℹ compiling from source
  ✔ pngquant pre-build test passed successfully
/home/hasura/Videos/UIBuilder/structor/node_modules/onetime/index.js:15
				throw new Error(fnName + ' can only be called once.');
				^

Error: callback() can only be called once.
    at onetime (/home/hasura/Videos/UIBuilder/structor/node_modules/onetime/index.js:15:11)
    at /home/hasura/Videos/UIBuilder/structor/node_modules/download/index.js:156:5
    at ConcatStream.<anonymous> (/home/hasura/Videos/UIBuilder/structor/node_modules/concat-stream/index.js:37:43)
    at emitNone (events.js:111:20)
    at ConcatStream.emit (events.js:208:7)
    at finishMaybe (/home/hasura/Videos/UIBuilder/structor/node_modules/readable-stream/lib/_stream_writable.js:630:14)
    at endWritable (/home/hasura/Videos/UIBuilder/structor/node_modules/readable-stream/lib/_stream_writable.js:638:3)
    at ConcatStream.Writable.end (/home/hasura/Videos/UIBuilder/structor/node_modules/readable-stream/lib/_stream_writable.js:594:41)
    at DuplexWrapper.onend (/home/hasura/Videos/UIBuilder/structor/node_modules/readable-stream/lib/_stream_readable.js:577:10)
    at Object.onceWrapper (events.js:313:30)

```

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pngquant-bin@4.0.0 postinstall: `node lib/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pngquant-bin@4.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by AbdeladimSadiki** [comment]
@yashwanth2804 

I am on Ubuntu 18.10, I had the same issue, this is how I resolved it:
1/ sudo apt-get install libpng-dev
2/ npm install -g pngquant-bin
3/ sudo rm -rf node_modules
4/ npm install
