### ISSUE TITLE
Module build failed: ReferenceError: [BABEL] on tutorial clone step

### ISSUE THREAD

**Issue by adambro** [ipselon/structor#31]
After trying out the tutorial and cloning project from webapp I've got following error:
```
[[["./.structor/src/PageForDesk.js","Module build failed: ReferenceError: [BABEL] /tmp/structor-tutorial/.structor/src/PageForDesk.js: Unknown option: base.stage"," at Logger.error (/tmp/structor-tutorial/node_modules/babel-core/lib/transformation/file/logger.js:41:11)"," at OptionManager.mergeOptions (/tmp/structor-tutorial/node_modules/babel-core/lib/transformation/file/options/option-manager.js:262:18)"," at OptionManager.init (/tmp/structor-tutorial/node_modules/babel-core/lib/transformation/file/options/option-manager.js:416:10)"," at File.initOptions (/tmp/structor-tutorial/node_modules/babel-core/lib/transformation/file/index.js:191:75)"," at new File (/tmp/structor-tutorial/node_modules/babel-core/lib/transformation/file/index.js:122:22)"," at Pipeline.transform (/tmp/structor-tutorial/node_modules/babel-core/lib/transformation/pipeline.js:42:16)"," at transpile (/tmp/structor-tutorial/node_modules/babel-loader/index.js:14:22)"," at /tmp/structor-tutorial/node_modules/babel-loader/lib/fs-cache.js:140:16"," at ReadFileContext.callback (/tmp/structor-tutorial/node_modules/babel-loader/lib/fs-cache.js:27:23)"," at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:324:13)"," @ multi main"]]]
```

**Comment by ipselon** [comment]
There is issue with babel. Look here https://github.com/babel/babel-loader/issues/132
It seems that I need to set strict number for babel versions in structor's package.json

**Comment by adambro** [comment]
IMHO good idea with strict numbers.

**Comment by ipselon** [comment]
Yes, but not today :-( Could you wait 1 day?

**Comment by adambro** [comment]
Sure, no problem. BTW: I've tried using strict numbers in package.json but got exacltly the same errors as in #32 afterwards.

OK, I've set exact versions and run `npm i`. 
```
  "devDependencies": {
    "babel-core": "6.3.26",
    "babel-loader": "6.2.0",
    "babel-plugin-add-module-exports": "0.1.2",
    "babel-plugin-transform-runtime": "6.3.13",
    "babel-polyfill": "6.3.14",
    "babel-preset-es2015": "6.3.13",
    "babel-preset-react": "6.3.13",
    "babel-preset-stage-0": "6.3.13"
}
```

**Comment by adambro** [comment]
> Sorry, I thought this is the same issue because you gave a reference. This case I need to investigate. Could you tell did reinstalling babel modules help for issue #31?

Yes, pinned version solved the problem. Closing.

**Comment by karimcse91** [comment]
adambro Thank you very much
