### ISSUE TITLE
How to run without global install

### ISSUE THREAD

**Issue by jdarling** [ipselon/structor#58]
Is there a way to run structor without installing it globally?  I would like to put in on a server and play with it but due to restrictions we don't install things globally, only locally (git clone, npm install, npm run).

When I try this I get an error:

```
Error: Cannot find module './server/controller.js'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/jdarling/structor/structor/structor.js:22:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
```

Is this due to a rewrite in progress, and if so what is the proper git tag, or should I just git checkout v1.0.8?

**Comment by jdarling** [comment]
And now I know I'm an idiot.  But for others:

```
git clone git@github.com:ipselon/structor.git
npm install
npm run build-server
node ./structor.js -p <path-to-project>
```
