### ISSUE TITLE
structor no longer able to create non react-boilerplate projects

### ISSUE THREAD

**Issue by rodenp** [ipselon/structor#70]
After updating structor to the latest version 2.0.0, it is no longer possible to create the old project types such as:

material-ui-prepack
bootstrap-prepack
structor-starter-prepack

Prior to this release, it was possible to run structor from within an empty directory and download a project. 

when typing structor i get the following errors:

Error: Cannot find module 'webpack'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Peter\AppData\Roaming\npm\node_modules\structor\server\structor\middlewareCompilerManager.js:1:1783)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)

**Comment by ipselon** [comment]
@rodenp Take a look at Structors readme. Beginning from v 2.0.0 Structor is integrated with react-boilerplate project. And all other previously used projects will be deprecated.

**Comment by rodenp** [comment]
This raises a number of questions.
1. How do i get access to the previous components that were part of the older projects? Like for example bootstrap buttons?2. How do i use generators that are part of the older projects? 3. How do you create new generators?
Some examples would be really helpful
thanksPeter
Date: Mon, 5 Sep 2016 08:12:15 -0700

**Comment by ipselon** [comment]
@rodenp 

> How do i get access to the previous components that were part of the older projects?

The prevous versions of Structor is working fine with Structor Market, so you are able to use them further. Of course, in the future such the possibility will be deprecated. But, it will be implemented almost the same mechanizm for creating and publishing generators by that time.

> How do you create new generators?

I'll try to implement the same feature as the previous version has for the current one - you'll be able to create and publish own components, but a bit easier. Can not give you an estimation when it will be, but definitely till the end of this month.

**Comment by AvaKathrynShaw** [comment]
Hi,

I just starting using React/Redux and found structor today so I have no problems with older versions of projects or of structor. I created an empty directory and used "npm install express" than installed structor but when attempting to run it I came across the same issue here. It was actually resolved by running "npm install webpack-g" BUT than I got a new error:

module.js:327
    throw err;
    ^

Error: Cannot find module 'webpack-dev-middleware'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\Ava\AppData\Roaming\npm\node_modules\structor\server\structor\middlewareCompilerManager.js:1:1867)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)


So logically I ran "npm install webpack-dev-middleware" and tried to run structor again but it didn't work. I double check my directory and both the webpack and webpack-dev-middleware modules exist. I tried uninstalling and reinstalling structor and running it again and it still is giving me the same error. 

Just wanted to give my input too! Let me know if you have any advice, thanks! 

P.S. Super excited to try it out!

**Comment by Dmytro-Medzatiy** [comment]
@AvaKathrynShaw the last version of Structor works only with react-boilerplate - at the moment there is no other way to start a new project. Please, find instructions how to start at https://github.com/ipselon/react-boilerplate readme file

**Comment by ipselon** [comment]
@AvaKathrynShaw, I added the ability to run Structor in any (or even empty) project directory. Please review Structor's Readme. Thanks.
