### ISSUE TITLE
Cannot find module 'lodash/defaultsDeep' at the first `npm run setup`

### ISSUE THREAD

**Issue by tyv** [ipselon/structor#78]
1. clone master
2. run `npm run setup`

```
module.js:327
    throw err;
    ^

Error: Cannot find module 'lodash/defaultsDeep'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/yuriyt/projects/react-boilerplate/internals/scripts/dependencies.js:15:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
```

**Comment by ipselon** [comment]
@tyv, just wrote down a https://github.com/ipselon/structor/issues/77#issuecomment-257698866 about how to solve this issue. Thanks.
