### ISSUE TITLE
Error on access

### ISSUE THREAD

**Issue by Trion** [ipselon/structor#8]
Hi,
everytime I try to acces http://localhost:2222/structor I the following error message is printed on my terminal:
~~~
ReferenceError: Promise is not defined
    at e._createClass.value (/usr/lib/node_modules/structor/server/FileManager.js:1:4416)
    at e._createClass.value (/usr/lib/node_modules/structor/server/StorageManager.js:1:8344)
    at e._createClass.value (/usr/lib/node_modules/structor/server/api.js:1:4064)
    at /usr/lib/node_modules/structor/server/api.js:1:3507
    at Layer.handle [as handle_request] (/usr/lib/node_modules/structor/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/lib/node_modules/structor/node_modules/express/lib/router/route.js:131:13)
    at /usr/lib/node_modules/structor/node_modules/body-parser/lib/read.js:129:5
    at invokeCallback (/usr/lib/node_modules/structor/node_modules/raw-body/index.js:262:16)
    at done (/usr/lib/node_modules/structor/node_modules/raw-body/index.js:251:7)
    at IncomingMessage.onEnd (/usr/lib/node_modules/structor/node_modules/raw-body/index.js:308:7)
ReferenceError: Promise is not defined
    at e._createClass.value (/usr/lib/node_modules/structor/server/FileManager.js:1:4704)
    at e._createClass.value (/usr/lib/node_modules/structor/server/StorageManager.js:1:1680)
    at e._createClass.value (/usr/lib/node_modules/structor/server/api.js:1:5012)
    at /usr/lib/node_modules/structor/server/api.js:1:3507
    at Layer.handle [as handle_request] (/usr/lib/node_modules/structor/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/lib/node_modules/structor/node_modules/express/lib/router/route.js:131:13)
    at /usr/lib/node_modules/structor/node_modules/body-parser/lib/read.js:129:5
    at invokeCallback (/usr/lib/node_modules/structor/node_modules/raw-body/index.js:262:16)
    at done (/usr/lib/node_modules/structor/node_modules/raw-body/index.js:251:7)
    at IncomingMessage.onEnd (/usr/lib/node_modules/structor/node_modules/raw-body/index.js:308:7)
ReferenceError: Promise is not defined
    at e._createClass.value (/usr/lib/node_modules/structor/server/Client.js:1:1453)
    at e._createClass.value (/usr/lib/node_modules/structor/server/ClientManager.js:1:1506)
    at e._createClass.value (/usr/lib/node_modules/structor/server/api.js:1:4449)
    at /usr/lib/node_modules/structor/server/api.js:1:3507
    at Layer.handle [as handle_request] (/usr/lib/node_modules/structor/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/lib/node_modules/structor/node_modules/express/lib/router/route.js:131:13)
    at /usr/lib/node_modules/structor/node_modules/body-parser/lib/read.js:129:5
    at invokeCallback (/usr/lib/node_modules/structor/node_modules/raw-body/index.js:262:16)
    at done (/usr/lib/node_modules/structor/node_modules/raw-body/index.js:251:7)
    at IncomingMessage.onEnd (/usr/lib/node_modules/structor/node_modules/raw-body/index.js:308:7
~~~

**Comment by ipselon** [comment]
What version of node.js you are using ?

**Comment by Trion** [comment]
I got v0.10.25.

**Comment by ipselon** [comment]
version of node should be >= 0.12.2

**Comment by Trion** [comment]
Thanks :)
