### ISSUE TITLE
Issue while installation

### ISSUE THREAD

**Issue by saisasankparimi** [ipselon/structor#88]
/react/structor-starter/node_modules/structor/postexec.js:57
			let packageFileName = packageVersion + META_REPO_ARCHIVE_EXT;
			^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:404:25)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:138:18)
    at node.js:974:3

**Comment by ipselon** [comment]
@saisasankparimi, it seems that your NodeJS version is < 5. Try to update NodeJS up to > 5

**Comment by saisasankparimi** [comment]
@ipselon my current Nodejs version is 5.1.0.

**Comment by ipselon** [comment]
@saisasankparimi sorry for misunderstanding, I meant 6 version and more...
